package dns

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// --- parseNameservers ---

func TestParseNameservers_realServers(t *testing.T) {
	f := writeTempFile(t, `
# Generated by NetworkManager
nameserver 192.168.1.1
nameserver 8.8.8.8
`)
	got := parseNameservers(f)
	want := []string{"192.168.1.1", "8.8.8.8"}
	assertSliceEqual(t, got, want)
}

func TestParseNameservers_skipsLoopback(t *testing.T) {
	f := writeTempFile(t, `
nameserver 127.0.0.1
nameserver 127.0.0.53
nameserver ::1
nameserver 10.0.0.1
`)
	got := parseNameservers(f)
	want := []string{"10.0.0.1"}
	assertSliceEqual(t, got, want)
}

func TestParseNameservers_onlyLoopback(t *testing.T) {
	f := writeTempFile(t, "nameserver 127.0.0.53\n")
	got := parseNameservers(f)
	if len(got) != 0 {
		t.Errorf("expected empty, got %v", got)
	}
}

func TestParseNameservers_missingFile(t *testing.T) {
	got := parseNameservers("/nonexistent/resolv.conf")
	if got != nil {
		t.Errorf("expected nil for missing file, got %v", got)
	}
}

func TestParseNameservers_skipsZonedLinkLocal(t *testing.T) {
	f := writeTempFile(t, `
nameserver fe80::46d4:53ff:fe3f:a9a7%18
nameserver fe80::1%eth0
nameserver 8.8.8.8
`)
	got := parseNameservers(f)
	want := []string{"8.8.8.8"}
	assertSliceEqual(t, got, want)
}

func TestSanitizeDNSIP(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"8.8.8.8", "8.8.8.8"},
		{"  1.1.1.1  ", "1.1.1.1"},
		{"169.254.1.1", "169.254.1.1"},
		{"2606:4700:4700::1111", "2606:4700:4700::1111"},
		{"127.0.0.1", ""},
		{"127.0.0.53", ""},
		{"::1", ""},
		{"0.0.0.0", ""},
		{"", ""},
		{"--", ""},
		{"not-an-ip", ""},
		{"fe80::46d4:53ff:fe3f:a9a7%18", ""},
		{"fe80::1%eth0", ""},
	}
	for _, c := range cases {
		if got := sanitizeDNSIP(c.in); got != c.want {
			t.Errorf("sanitizeDNSIP(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestParseNameservers_commentsIgnored(t *testing.T) {
	f := writeTempFile(t, `
# This is a comment
; another comment
search example.com
nameserver 1.1.1.1
`)
	got := parseNameservers(f)
	want := []string{"1.1.1.1"}
	assertSliceEqual(t, got, want)
}

// --- isFileContent ---

func TestIsFileContent_match(t *testing.T) {
	f := writeTempFile(t, "hello world")
	if !isFileContent(f, []byte("hello world")) {
		t.Error("expected match")
	}
}

func TestIsFileContent_mismatch(t *testing.T) {
	f := writeTempFile(t, "hello world")
	if isFileContent(f, []byte("different")) {
		t.Error("expected mismatch")
	}
}

func TestIsFileContent_missingFile(t *testing.T) {
	if isFileContent("/nonexistent/file", []byte("x")) {
		t.Error("expected false for missing file")
	}
}

// --- helpers ---

func writeTempFile(t *testing.T, content string) string {
	t.Helper()
	f, err := os.CreateTemp(t.TempDir(), "resolv-*.conf")
	if err != nil {
		t.Fatal(err)
	}
	f.WriteString(content)
	f.Close()
	return f.Name()
}

func assertSliceEqual(t *testing.T, got, want []string) {
	t.Helper()
	if len(got) != len(want) {
		t.Errorf("got %v, want %v", got, want)
		return
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("index %d: got %q, want %q", i, got[i], want[i])
		}
	}
}

func assertContains(t *testing.T, s, substr string) {
	t.Helper()
	if !strings.Contains(s, substr) {
		t.Errorf("expected %q to contain %q", s, substr)
	}
}

// writeGlobalConfig points XDG_CONFIG_HOME at a fresh temp dir and writes the
// given YAML as the lerd global config there, so config.LoadGlobal picks it up.
func writeGlobalConfig(t *testing.T, yaml string) {
	t.Helper()
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)
	lerdDir := filepath.Join(dir, "lerd")
	if err := os.MkdirAll(lerdDir, 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(lerdDir, "config.yaml"), []byte(yaml), 0644); err != nil {
		t.Fatal(err)
	}
}

func TestNormalizeUpstreamEntry(t *testing.T) {
	cases := []struct {
		in   string
		want string
		ok   bool
	}{
		{"192.168.100.129", "192.168.100.129", true},
		{" 8.8.8.8 ", "8.8.8.8", true},
		{"1.1.1.1#5353", "1.1.1.1#5353", true},
		{"2001:db8::1", "2001:db8::1", true},
		{"2001:db8::1#53", "2001:db8::1#53", true},
		{"8.8.8.8#0", "", false},
		{"8.8.8.8#-5", "", false},
		{"8.8.8.8#99999", "", false},
		{"8.8.8.8#abc", "", false},
		{"127.0.0.1", "", false},
		{"not-an-ip", "", false},
		{"", "", false},
	}
	for _, c := range cases {
		got, ok := NormalizeUpstreamEntry(c.in)
		if ok != c.ok || got != c.want {
			t.Errorf("NormalizeUpstreamEntry(%q) = (%q,%v), want (%q,%v)", c.in, got, ok, c.want, c.ok)
		}
	}
}

func TestConfiguredUpstreamDNS_returnsPinnedServers(t *testing.T) {
	writeGlobalConfig(t, "dns:\n  upstream:\n    - 192.168.100.129\n    - 10.0.0.1\n")
	got := configuredUpstreamDNS()
	assertSliceEqual(t, got, []string{"192.168.100.129", "10.0.0.1"})
}

func TestConfiguredUpstreamDNS_preservesPortSuffix(t *testing.T) {
	writeGlobalConfig(t, "dns:\n  upstream:\n    - 192.168.100.129#5353\n")
	got := configuredUpstreamDNS()
	assertSliceEqual(t, got, []string{"192.168.100.129#5353"})
}

func TestConfiguredUpstreamDNS_skipsLoopbackAndJunk(t *testing.T) {
	writeGlobalConfig(t, "dns:\n  upstream:\n    - 127.0.0.1\n    - not-an-ip\n    - 8.8.8.8\n")
	got := configuredUpstreamDNS()
	assertSliceEqual(t, got, []string{"8.8.8.8"})
}

func TestConfiguredUpstreamDNS_emptyWhenUnset(t *testing.T) {
	writeGlobalConfig(t, "dns:\n  tld: test\n")
	if got := configuredUpstreamDNS(); len(got) != 0 {
		t.Errorf("expected no upstreams, got %v", got)
	}
}
